### ISSUE TITLE
countdown has wrong time

### ISSUE THREAD

**Issue by lnussel** [openSUSE/landing-page#113]
assets/js/countdown.js specifies Europe/Berlin as time zone for the countdown. Must be UTC.

If < 1 hour the countdown says available now which doesn't make sense. It either needs to stick with one hour or say something like "soon"

**Comment by cyntss** [comment]
I made it this way because I had no clear information if the links where going to be updated a a precise time or not.

Saying "soon" makes less sense yet, since we have a countdown, users will expect that countdown to finish and provide the information. A "soon" would be providing no specification whatsoever, the user will have a big unknown in their screens.

So, my proposal is, if you are 100% sure that we will publish everything at the exact time (or before) the countdown finishes, then we can count the minutes and then the seconds of the last hour. That way we are providing a meaningful countdown.

**Comment by lnussel** [comment]
The downloads are ready and open latest at the specified time, usually a few minutes before. So counting down on minute basis also would work.

**Comment by lnussel** [comment]
I fixed the time zone now myself. Any update on the calculation?

**Comment by lkocman** [comment]
I see that no-one is assigned to the issue. I made this issue part of our retro etherpad here https://etherpad.opensuse.org/p/ReleaseEngineering-Leap-15.2-retro-20200706
