### ISSUE TITLE
error beyond the landing page

### ISSUE THREAD

**Issue by ddemaio** [openSUSE/landing-page#151]
@cyntss  When navigating beyond (and from) the landing page selecting the
catalan language, an error message appears:

(<unknown>): mapping values are not allowed in this context at line 1 column 21

Is this due to a bad translated string or is it the page? Does it need
some refreshing?

Catalan team would like to know.

**Comment by Davidmp1** [comment]
See this page selecting catalan version:
 
https://software.opensuse.org/distributions/leap

And then try any other language. What is wrong?

David M.
Catalan team

**Comment by cyntss** [comment]
@ddemaio @Davidmp1  you need to report this error to the people maintaining the software page. The landing page does not have the Catalan language for what I can see.

**Comment by Davidmp1** [comment]
Hello,

And who is the people maintaining the landing page? Could you point them to
us?
The landing page and the pages beyond have had the Catalan language
available and 100 % translated until now. You can not see it now because
there is an error somewhere and this is an attempt to report it and correct
it.

In the meantime, I have filed a bug report:
https://bugzilla.opensuse.org/show_bug.cgi?id=1136684

Please, if the bug report is not assigned to the right people, contribute
to make it right.

Thanks.

David Medina
Catalan team



Missatge de Cynthia Sanchez <notifications@github.com> del dia dt., 28 de
maig 2019 a les 14:52:

**Comment by cyntss** [comment]
@Davidmp1 you are right about the landing page having Catalan, but I cannot see any problem here:

![image](https://user-images.githubusercontent.com/5013096/58561585-b6940480-8227-11e9-8614-a96581916a53.png)

I don't know who maintains the Software page (where the problem is visible) and don't know which repository it is, but the bug belongs there. @ddemaio do you know?

**Comment by Davidmp1** [comment]
Hello,

Ok, to be precise, I have changed the bug's title to "Software page", since
you say that it belongs to a different resource.
I hope it gets corrected soon.

Thanks.

Missatge de Cynthia Sanchez <notifications@github.com> del dia dc., 29 de
maig 2019 a les 15:38:
