### ISSUE TITLE
Conferences

### ISSUE THREAD

**Issue by manugupt1** [openSUSE/landing-page#32]
Hi 

Do you plan to publicize conferences like the current what's new in the landing pages which are already uploaded?

If so, can you include a promotion text for openSUSE.Asia summit too?

Regards
Manu

**Comment by tigerfoot** [comment]
Hi Manu @manugupt1  would you mind point the PR you made against the actual landing page
@cyntss : it's true that the actual project is missing a placeholder for news and countdown 
Could it be possible to have  a hack on them ?

**Comment by manugupt1** [comment]
This was the PR I opened up. 
https://github.com/openSUSE/landing-page/pull/21

**Comment by cyntss** [comment]
The news are read via the xml file generated by wordpress. if that is  what you mean :)

at the moment.. of course I cannot read the xml because im not in the server, thus, i have an static xml just to emulate the news, but once someone uploads the files to the server, they will simply change a line in the .js file handling the news from to https://news.opensuse.org/feed

I hope that is what you mean

**Comment by tigerfoot** [comment]
@manugupt1  tx for the pointer inside the new website I don't see and kind of whats_hot zone as we had previously ... So this issue is not resolved yet and also a counter section somewhere look missing.

@cyntss I think that the xml could be already plugged to the news feed it should work normally.

**Comment by cyntss** [comment]
@tigerfoot It doesnt work as expected since news.opensuse.org is not allowing access to red the XML from external domains. I didnt consider www.opensuse.org was going to be considered a different domain, but it is a different subdomain so yes.

The solution I find to be the best one to stick to Front-end is: https://github.com/jpillora/xdomain 

Let me know if you can implement the proxy.html inside news.opensuse.org and then I implement the rest in this side and that will be it.

**Comment by cyntss** [comment]
This was already fixed and the countdown wont be implemented but something different will come. This last issue will be kept track of at https://github.com/openSUSE/landing-page/issues/86
